config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: 'pages#home'
  get 'about_us', to: 'pages#about_us'
  get 'contact_us', to: 'pages#contact_us'
  get 'for_businesses', to: 'pages#for_businesses'
  
  resource :dashboard, only: :show
  resource :subscription, only: :show
  
  resources :companies, only: [ :index, :show, :edit, :update ] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  include PgSearch::Model

  belongs_to :user, optional: true
  has_many :reviews

  pg_search_scope :global_search,
    against: [ :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  validates :name, :email, :country, :website, presence: true

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :company

  validates :email, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :company
  attr_accessor :email

  validates :score, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :company, optional: true
  has_many :reviews

  validates :first_name, :last_name, presence: true


  def admin?
    role == 'admin'
  end

  def owner?
    role == 'owner' || company.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    skip_before_action :authenticate_user!, only: [ :index, :show ]
    before_action :set_company, only: [:edit, :show ]

    def index
        if params[:query].present?
            @companies = Company.global_search(params[:query])
        else
            @companies = Company.all
        end
    end

    def show
        @review = Review.new
    end

    def edit; end

    def update; end

    private

    def set_company
        @company = Company.find(params[:id])
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :about_us, :contact_us, :for_businesses ]

  def home; end

  def about_us; end

  def contact_us; end

  def for_businesses; end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :authenticate_user!, only: [ :product ]

    def show; end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :create, :new ]
  before_action :set_company, only: %i[new create]

  def new
    @company = Company.find(params[:company_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.company             = @company
    @review.verification_status = 'unverified'
    @review.source              = 'website'
    # @review.user                = User.find_or_create_by(email: review_params[:email])

    if @review.save
      redirect_to company_path(@company)
    else
      render 'companies/show', status: :unprocessable_entity
    end
  end

  private

  def set_company
    @company = Company.find(params[:company_id])
  end

  def review_params
    params.require(:review).permit(:title, :description, :order_id, :score, :email)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/edit.html.erb
<h2> Edit <%= @company.name %> </h2>

app/views/companies/index.html.erb
<h2>All Companies</h2>

<ul>
    <% @companies.each do |company| %>
        <li> <%= link_to company.name, company_path(company) %> </li>
    <% end %>
</ul>

app/views/companies/show.html.erb
<h2> <%= @company.name %> </h2>

<%= render 'reviews/new' %>

<h4>Reviews</h4>

<% @company.reviews.each do |review| %>
  <%= review.title %>
  <%= review.description %>
  <%= review.score %>
<% end %>


<script type="application/ld+json">
  <% graph = [] %>

  <% company = LocalBusinessPresenter.new(@company) %>
  <% graph.append(company.to_schema) %>

  <% @company.reviews.each do |r| %>
    <% review = ReviewPresenter.new(r) %>
    <% graph.append(review.to_schema) %>
    <% # This needs to be generated only for the reviews of the page. %>
  <% end %>

  <% schema = {
    "@context": "https://schema.org",
    "@graph": graph
    } %>
  <%= schema.to_json.html_safe %>

</script>

app/views/dashboards/show.html.erb
<h2>Dashboard</h2>

<%= link_to 'Subscription', subscription_path, class: 'btn btn-primary' %>

<% if current_user.owner? %>
    <%= link_to 'Edit Company Details', edit_company_path(current_user.company), class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Opinamos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<h2>About Us</h2>

app/views/pages/contact_us.html.erb
<h2>Contact Us</h2>

app/views/pages/for_businesses.html.erb
<div class="container py-4">

    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Comienza a recolectar opiniones reales de tus clientes</h1>
        <p class="col-md-8 fs-4">Inspira confienza y gana más ventas.</p>
        <button class="btn btn-primary btn-lg" type="button">Comienza ahora!</button>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <h2>Aumenta tu posicionamiento orgánico en Google</h2>
      </div>
      <div class="col-md-4">
        <h2>Muestra tus calificaciones para más ventas</h2>
      </div>
      <div class="col-md-4">
        <h2>Incrementa tus clicks y tasa de conversión</h2>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Calificaciones de marca</h2>
          <p>Obtén calificaciones de tu marca.</p>
          <button class="btn btn-outline-light" type="button">Ver detalles</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Calificaciones de productos</h2>
          <p>Obtén calificaciones para cada uno de tus productos.</p>
          <button class="btn btn-outline-secondary" type="button">Ver detalles</button>
        </div>
      </div>
    </div>

  </div>

app/views/pages/home.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Compra con confienza. Encuentra calificaciones de tus empresas favoritas.</h1>
      </div>
      <div class="w-25">
          <%= form_with url: companies_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Search for companies"
          %>
          <%= submit_tag "Search", class: "btn btn-primary" %>
          <% end %>
      </div>
      <%= link_to 'All Companies', companies_path, class: 'btn btn-primary' %>
</div>

app/views/reviews/_new.html.erb
<h4>Add a new review!</h4>

<%= simple_form_for [@company, @review] do |f| %>
    <%= f.input :title %>
    <%= f.input :order_id %>
    <%= f.input :description %>
    <%= f.input :score %>
    <%= f.input :email %>
    <%= f.submit "Submit Review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <%= form_with url: companies_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for companies"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", about_us_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact Us", contact_us_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "For Businesses", for_businesses_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/subscriptions/show.html.erb
<h2>Subscription</h2>